name: buf
on:
  push:
    paths:
      - 'proto/**'
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.28.0
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1.1.0
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
  breaking:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.28.0
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-breaking-action@v1.1.3
        with:
          against: buf.build/coobeet/coobeet
          buf_token: ${{ secrets.BUF_TOKEN }}
  push:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - breaking
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.28.0
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-push-action@v1.2.0
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
